Add PR preview deploys - just add the deploy label
1) Deploy PRs to pr_num.pr.posthog.cc when the deploy label is added to
   a PR. Also deploy updates on push
2) Use the GitHub deploy API to nicely showcase this
3) Handle cleanup of the deployment when the PR is merged or closed

diff --git a/.github/workflows/pr-deploy-cleanup.yaml b/.github/workflows/pr-deploy-cleanup.yaml
--- a/.github/workflows/pr-deploy-cleanup.yaml
+++ b/.github/workflows/pr-deploy-cleanup.yaml
@@ -1,18 +1,9 @@
-# This workflow handles deploying a branch to the pull request cluster, for
-# testing purposes. It is locked down so that it can only be used by people who
-# are a member of the PostHog Github org
-
-name: PR - Preview Deploy
-
 on:
   pull_request:
-    types: 
-      - labeled
-      - synchronize
-
+    types: [closed]
 jobs:
-  deploy:
-    name: Deploy Preview
+  cleanup:
+    name: Cleanup merged deploy
     runs-on: ubuntu-latest
     steps:
       - name: Check user permission
@@ -31,7 +22,7 @@ jobs:
         run: hub pr checkout ${{ github.event.number }} # github cli is pre installed
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
+        if: ${{ steps.check.outputs.has-permission && github.event.label.name == 'deploy' }} 
 
       - name: Declare variables that we can share across steps
         id: vars
@@ -42,51 +33,37 @@ jobs:
           echo "::set-output name=git_short::${GIT_SHORT}"
           echo "::set-output name=fqdn_record::${PR_NUM}.pr.posthog.cc"
           echo "::set-output name=pr_number::${PR_NUM}"
-        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
-
-      - name: start deployment
-        uses: bobheadxi/deployments@v1
-        id: deployment
-        with:
-          step: start
-          token: ${{ secrets.GITHUB_TOKEN }}
-          env: ${{ github.head_ref }}
-          ref: ${{ github.head_ref }}
+          echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
         if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
 
       - name: Install doctl to access k8s config
         uses: digitalocean/action-doctl@v2
         with:
           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
-        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
 
-      - name: Install PostHog using the Helm chart
-        id: helm_install
+      # Only ran if the correct comment is used! We should have automatic cleanup on merge, but this allows us to manually
+      # cleanup. For instance, you may restore a branch, deploy it, and keep it around for demo purposes.
+      - name: Delete preview namespace
+        id: delete_preview
         run: |
           doctl kubernetes cluster kubeconfig save $PR_CLUSTER_ID 
 
-          helm upgrade --install \
-            -f ci/values/pr/values.yaml \
-            --set ingress.hostname=${{ steps.vars.outputs.fqdn_record }} \
-            --timeout 30m \
-            --create-namespace \
-            --namespace pr-${{ steps.vars.outputs.pr_number }} \
-            posthog ./charts/posthog \
-            --wait \
-            --wait-for-jobs 
+          kubectl patch chi posthog -n pr-${{ steps.vars.outputs.pr_number }} -p '{"metadata":{"finalizers":null}}' --type=merge || true # if the resource cannot be found, we still want to clean up
+          helm uninstall -n pr-${{ steps.vars.outputs.pr_number }} posthog
+          
+          # delete all instances of all resources, in the specified namespace
+          # just in case someone has made a change to the chart that stops uninstall cleaning up correctly
+          kubectl delete all --all --namespace pr-${{ steps.vars.outputs.pr_number }}
+          kubectl delete namespace pr-${{ steps.vars.outputs.pr_number }}
+
         if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
         env:
           PR_CLUSTER_ID: ${{ secrets.PR_CLUSTER_ID }} # probably not _SECRET_, but best kept out of the YAML
 
-      - name: update deployment status
+      - name: mark environment as deactivated
         uses: bobheadxi/deployments@v1
         with:
-          step: finish
+          step: deactivate-env
           token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ job.status }}
-          env: ${{ steps.deployment.outputs.env }}
-          ref: ${{ github.head_ref }}
-          env_url: https://${{ steps.vars.outputs.fqdn_record }}
-          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
-        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
-
+          env: ${{ steps.vars.outputs.branch_name }}
+          desc: Environment was pruned
